spring.application.name=api-gateway

server.port=8080

# ==============================
# Backend Services
# ==============================

services.auth.url=http://localhost:8081
services.timetable.url=http://localhost:8083
services.report.url=http://localhost:8084


# ==============================
# Gateway Routes
# ==============================

# AUTH SERVICE
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${services.auth.url}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**


# REPORT SERVICE
spring.cloud.gateway.server.webmvc.routes[1].id=report-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${services.report.url}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/reports/**


# ALL OTHER ACADEMIC APIs → TIMETABLE SERVICE
spring.cloud.gateway.server.webmvc.routes[2].id=timetable-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${services.timetable.url}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/**


# ==============================
# Actuator
# ==============================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# ==============================
# CORS
# ==============================

spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5500,http://127.0.0.1:5500
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.server.webmvc.globalcors.add-to-simple-url-handler-mapping=true